name: Build Java
on:
  push:
    branches:
      - main
      - renovate/**
jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./Java
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Set up Java
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'liberica'
          java-version: 25
          java-package: 'jdk'
          cache: maven

      - name: Run mvn clean verify
        run: mvn clean verify

      - name: Publish Surefire test report
        uses: dorny/test-reporter@v2.2.0
        if: always()
        with:
          name: Surefire Tests
          working-directory: ./Java
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
